insert into cities (name, slug, region)
values
  ('Beroun', 'beroun', 'Central Bohemian'),
  ('Kladno', 'kladno', 'Central Bohemian'),
  ('Most', 'most', 'Usti nad Labem'),
  ('Teplice', 'teplice', 'Usti nad Labem'),
  ('Chomutov', 'chomutov', 'Usti nad Labem'),
  ('Decin', 'decin', 'Usti nad Labem'),
  ('Mlada Boleslav', 'mlada-boleslav', 'Central Bohemian'),
  ('Benesov', 'benesov', 'Central Bohemian'),
  ('Pribram', 'pribram', 'Central Bohemian'),
  ('Kolin', 'kolin', 'Central Bohemian'),
  ('Kutna Hora', 'kutna-hora', 'Central Bohemian'),
  ('Nymburk', 'nymburk', 'Central Bohemian'),
  ('Podebrady', 'podebrady', 'Central Bohemian'),
  ('Tabor', 'tabor', 'South Bohemian'),
  ('Pisek', 'pisek', 'South Bohemian'),
  ('Strakonice', 'strakonice', 'South Bohemian'),
  ('Cesky Krumlov', 'cesky-krumlov', 'South Bohemian'),
  ('Trutnov', 'trutnov', 'Hradec Kralove'),
  ('Nachod', 'nachod', 'Hradec Kralove'),
  ('Jicin', 'jicin', 'Hradec Kralove'),
  ('Chrudim', 'chrudim', 'Pardubice'),
  ('Svitavy', 'svitavy', 'Pardubice'),
  ('Ceska Lipa', 'ceska-lipa', 'Liberec'),
  ('Jablonec nad Nisou', 'jablonec-nad-nisou', 'Liberec'),
  ('Turnov', 'turnov', 'Liberec'),
  ('Cheb', 'cheb', 'Karlovy Vary'),
  ('Sokolov', 'sokolov', 'Karlovy Vary'),
  ('Litomerice', 'litomerice', 'Usti nad Labem'),
  ('Lovosice', 'lovosice', 'Usti nad Labem'),
  ('Varnsdorf', 'varnsdorf', 'Usti nad Labem'),
  ('Frydek-Mistek', 'frydek-mistek', 'Moravian-Silesian'),
  ('Havirov', 'havirov', 'Moravian-Silesian'),
  ('Karvina', 'karvina', 'Moravian-Silesian'),
  ('Opava', 'opava', 'Moravian-Silesian'),
  ('Prerov', 'prerov', 'Olomouc'),
  ('Prostejov', 'prostejov', 'Olomouc'),
  ('Vyskov', 'vyskov', 'South Moravian'),
  ('Kromeriz', 'kromeriz', 'Zlin'),
  ('Uherske Hradiste', 'uherske-hradiste', 'Zlin'),
  ('Hodonin', 'hodonin', 'South Moravian'),
  ('Breclav', 'breclav', 'South Moravian'),
  ('Znojmo', 'znojmo', 'South Moravian'),
  ('Trebic', 'trebic', 'Vysocina'),
  ('Havlickuv Brod', 'havlickuv-brod', 'Vysocina')
on conflict (slug) do nothing;
